calculate_route.settings:
  title: 'Calculate Route Settings'
  description: 'Calculate Route Settings Description little short.'
calculate_route.config.api_key:
  title: 'Api Key'
  description: 'Api Key Description little short.'
calculate_route.config.map:
  title: 'Default Map'
  description: 'Default Map Description little short.'
calculate_route.config.marker:
  title: 'Default Marker'
  description: 'Default Marker Description little short.'
calculate_route.config.form:
  title: 'Default Form'
  description: 'Default Form Description little short.'
calculate_route.config.appearence:
  title: 'Default Appearence'
  description: 'Default Appearence Description little short.'
